name: My Blog
markdown: redcarpet
pygments: true
baseurl: "http://anupvarghese.github.io/blog"
markdown: kramdown

description: A stylish blog using the Solarized color palette

permalink: /:year/:month/:day/:title/
paginate: 10

safe: true
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']